---
language: go

go:
  - 1.4
  - tip

services:
  - rabbitmq

branches:
  only:
    - master

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc

install:
  - go get -u ./...

script:
 - go test -v ./...
